export const storeProducts = [
    {id: 1,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 2,
    title: "Small Lilac + Honey Candle",
    img: require("../src/images/small-lilac-honey.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 3,
    title: "Small Peony Candle",
    img: require("../src/images/small-peony.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 4,
    title: "Large Rose + Patchouli Candle",
    img: require("../src/images/large-rose-patchouli.png"),
    price: 15,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 5,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},
    
    {id: 6,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 7,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 8,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},

    {id: 9,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"},
]

export const detailProduct = [    
    {id: 1,
    title: "Small Alien Candle",
    img: require("../src/images/small-alien.png"),
    price: 10,
    info: 'lorem ipsum blah blah blah blah',
    inCart: false,
    count: 0,
    total: 0,
    color: "white"}]